version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: rag-postgres
    environment:
      POSTGRES_DB: rag_production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rag-app:
    build: .
    container_name: rag-application
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: rag_production
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SSL_MODE: disable
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LOG_LEVEL: info
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/root/logs

volumes:
  postgres_data:
    driver: local
